// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwyoiyeofaqkiiuyipzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13eW9peWVvZmFxa2lpdXlpcHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDE5ODcsImV4cCI6MjA2MTMxNzk4N30.PV5C2YbtLpNzgbmS7KljAuz2ydbtzdpA-MIU2fS-J7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);